### ISSUE TITLE
Getting 2 Items when crafting 1

### ISSUE THREAD

**Issue by Skulli73** [PixliesEarth/PixliesNet#36] opened 2020-12-21 19:47 UTC
Some times when crafting stuff in the Custom Machienes like a forge you can get 2 items of the stuff you craft even though you just crafted one

i dont know how to reproduce this

**Comment by BradBot1** [comment] 2020-12-22 12:08
I cannot reproduce this issue, if you can please record yourself doing it or give instructions on how to preform this issue. I will be closing this issue due to a lack of information.

**Closed as completed by BradBot1** 2020-12-22 12:08 UTC
Labels: Needs More Information
